color: null
description: 'Available Jobs'
fieldLayouts:
  b81cd04f-1f9f-49ae-9a9b-dd0c3e712818:
    cardThumbAlignment: start
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-05T17:36:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Job Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f689c2f1-55f0-4916-9c49-e97e7e3b75f6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-09T22:17:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a026cacb-2f40-4011-b87d-a1beb7552037 # Organization
            handle: listingOrganization
            includeInCards: false
            instructions: null
            label: 'Listing Organization'
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a88f10db-34c2-4551-bc98-ecec0053834d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-03T13:01:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b2206c41-3f40-4586-bca2-2bc4fb379556 # School
            handle: null
            includeInCards: false
            instructions: 'If this organization is a recruiter, then select the school to which this search applies.'
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a1f0dd6-dbf6-4166-9e84-e17e98f4221d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-05T17:57:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: db17bc24-8930-4e0e-ab38-c2565b80dae6 # Rich Text
            handle: jobDescription
            includeInCards: false
            instructions: null
            label: 'Job Description'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 500cabcc-1d4b-48d7-8634-188304b44557
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-05T17:57:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bb81f5b9-0813-4e6d-b693-229f093ce3e4 # Job Category
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1325d10-a40f-48fa-8d5e-eccd516c7197
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-05T17:57:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6407ff57-cf24-424a-8a4f-34c0137e2feb # Country
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28555537-042a-47b4-8dc0-eab0b7316e47
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-05T17:57:10+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 6407ff57-cf24-424a-8a4f-34c0137e2feb # Country
                  layoutElementUid: 28555537-042a-47b4-8dc0-eab0b7316e47
                  operator: in
                  uid: 4c62e50d-f5a5-4b76-ae90-8081754b8451
                  values:
                    - international
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 7a6fec95-2ed4-4d18-b669-9108357adc40 # Single Line Text
            handle: jobLocation
            includeInCards: false
            instructions: null
            label: 'Job Location'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d29406ff-5c3e-42aa-b96d-f8e9a53ef0d6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-05T18:25:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: afc27a98-498b-4fda-8c1e-c5eda8fcc52e # Job Region
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: daabeaee-9ea3-45bb-a883-1f95daaa51cf
            userCondition:
              class: craft\elements\conditions\users\UserCondition
              conditionRules:
                -
                  class: craft\elements\conditions\users\AdminConditionRule
                  uid: 89c490ee-4aa9-49e7-bace-353f65f123d9
                  value: true
              elementType: craft\elements\User
              fieldContext: global
            warning: null
            width: 100
          -
            dateAdded: '2025-09-05T17:57:10+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 6407ff57-cf24-424a-8a4f-34c0137e2feb # Country
                  layoutElementUid: 28555537-042a-47b4-8dc0-eab0b7316e47
                  operator: in
                  uid: 10949ec0-d632-435c-9b34-45eb46323792
                  values:
                    - unitedStates
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 7a6fec95-2ed4-4d18-b669-9108357adc40 # Single Line Text
            handle: jobCity
            includeInCards: false
            instructions: null
            label: City
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f30731f-93cb-4cb0-a493-3ab010e44712
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-17T13:14:12+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 6407ff57-cf24-424a-8a4f-34c0137e2feb # Country
                  layoutElementUid: 28555537-042a-47b4-8dc0-eab0b7316e47
                  operator: in
                  uid: 9a1803b0-fed2-44a4-ba5c-801f290c3810
                  values:
                    - unitedStates
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: f4e9368b-2d36-4ac5-b087-d0b8a3e8079f # State
            handle: jobState
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 335a4b12-0cd2-45b7-b8af-b8390a5fd7a7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-05T17:57:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7a6fec95-2ed4-4d18-b669-9108357adc40 # Single Line Text
            handle: jobSalaryLow
            includeInCards: false
            instructions: null
            label: 'Salary Low'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee6bd539-2826-4113-88b2-f52b8448cb3f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-05T17:57:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7a6fec95-2ed4-4d18-b669-9108357adc40 # Single Line Text
            handle: jobSalaryHigh
            includeInCards: false
            instructions: null
            label: 'Salary High'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf40d6af-d768-4efa-814e-a1a448f55484
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-05T17:57:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: db17bc24-8930-4e0e-ab38-c2565b80dae6 # Rich Text
            handle: jobOpportunityStatement
            includeInCards: false
            instructions: null
            label: 'Opportunity Statement'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab3e7095-da0f-4496-b2c4-fa194bd34026
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-05T17:57:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0d0aac89-9a3b-4d6e-add7-8a1c3a679b77 # Multi Line Text
            handle: jobApplicationInstructions
            includeInCards: false
            instructions: null
            label: 'Application Instructions'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 565af54b-500f-4fb5-8e14-6b9629348a96
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-05T18:11:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a7ace354-3f52-4d0a-87b1-96da5efcc457 # Job Attachments
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f3469e2-06f8-44d1-94a0-0e8d4545ca97
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-24T00:10:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1f0b0042-74ac-4177-b1cf-513c884f116a # Paid?
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72f35188-3df3-4a27-bce3-c8b24e30d61d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-16T12:47:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c35140bb-4530-44c6-be76-e4d189e69dd2 # Stripe Session ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e555ccce-2f7d-40a8-88dd-5f61b5d7c812
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-16T12:47:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 06ff70cf-8a32-453c-84c8-54a1c71e3e66 # Payment Type
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2ae3bab-96d3-4da8-99e5-3a199598c4bb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f738c44c-369c-424e-b286-ec843238c27c
        userCondition: null
handle: jobs
hasTitleField: true
icon: briefcase-blank
name: Jobs
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
