color: null
description: null
fieldLayouts:
  0df15160-a8f0-4582-a6de-70e37fc3f222:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-05T14:30:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c81e7721-da9d-4cb6-be6e-73ee501639e3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-05T14:32:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: db17bc24-8930-4e0e-ab38-c2565b80dae6 # Rich Text
            handle: body
            includeInCards: false
            instructions: null
            label: Body
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe2832d2-32f3-4ed5-8a9b-c139d64c82ed
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 73a26674-3921-42ef-999a-e2fbe611cdfd
        userCondition: null
handle: privacy
hasTitleField: true
icon: null
name: Privacy
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
