columnSuffix: null
handle: logo
instructions: null
name: Logo
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:5de740b2-aa13-48eb-b460-549297b24e7d' # Logos
  defaultUploadLocationSubpath: '{slug}'
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:5de740b2-aa13-48eb-b460-549297b24e7d' # Logos
  restrictedLocationSubpath: '{slug}'
  selectionLabel: 'Add an image'
  showCardsInGrid: false
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
