dateModified: 1762361301
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      heading: 'Content Sections'
      key: 'heading:b9543fed-514b-41c1-add8-d999d5487ca7'
      type: heading
    -
      defaultSort:
        - title
        - asc
      defaultViewMode: table
      disabled: false
      key: 'section:7a30d7ad-a979-44b7-89f1-35059c005316' # Organizations
      tableAttributes:
        - status
        - link
        - 'field:21bd4595-df6f-4876-9708-5bfadad51b42' # Website
        - 'field:12d880c0-a281-4f27-a40b-135b2f5b4654' # Type of Organization
        - authors
      type: native
    -
      defaultSort:
        - id
        - asc
      defaultViewMode: table
      disabled: false
      key: 'section:bfd2eaee-0f5f-44f6-81f2-1f5e563a0e2e' # Jobs
      tableAttributes:
        - 'field:b2206c41-3f40-4586-bca2-2bc4fb379556' # School
        - 'fieldInstance:a88f10db-34c2-4551-bc98-ecec0053834d'
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      heading: 'Single Pages'
      key: 'heading:8259d136-d1fe-4674-a2a5-56963b4cb307'
      type: heading
    -
      key: 'single:2fcab9d0-3904-4d93-95d0-870fccb5c2cc' # About
      type: native
    -
      defaultSort:
        - id
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'single:ac5e09a1-0209-46fa-bf18-00690e21c24e' # BGS Overview
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      key: 'single:64e2d70d-bf2d-4df4-9df4-be6545a2afc0' # Footer
      type: native
    -
      defaultSort:
        - id
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'single:c7caf5a7-983c-4d28-9e27-1a7829f7a221' # Homepage
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      key: 'single:9b7203f7-538c-4b6c-8119-9c33c258f2bc' # Privacy & Terms
      type: native
    -
      key: 'single:56d41606-0de2-4906-9d56-7a4b768399be' # Subscribe
      type: native
    -
      heading: ''
      key: 'heading:4bde67e5-7843-4723-8d24-805c7534d3fe'
      type: heading
    -
      heading: ''
      key: 'heading:c9af1b5a-92ed-406c-858f-601266c3ae56'
      type: heading
  craft\elements\User:
    -
      defaultSort:
        - lastName
        - asc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - fullName
      type: native
    -
      defaultSort:
        - id
        - asc
      defaultViewMode: ''
      disabled: false
      key: admins
      tableAttributes:
        - status
        - fullName
        - email
        - dateCreated
        - lastLoginDate
      type: native
    -
      heading: 'Account Type'
      key: 'heading:2981424f-c72b-41c9-a1b0-96b3cff022a6'
      type: heading
    -
      defaultSort:
        - id
        - asc
      defaultViewMode: ''
      disabled: false
      key: credentialed
      tableAttributes:
        - status
        - fullName
        - email
        - dateCreated
        - lastLoginDate
      type: native
    -
      defaultSort:
        - id
        - asc
      defaultViewMode: ''
      disabled: false
      key: inactive
      tableAttributes:
        - status
        - fullName
        - email
        - dateCreated
        - lastLoginDate
      type: native
    -
      heading: Groups
      key: 'heading:3b252fe0-6f0c-4c5b-a781-d5954e7ad469'
      type: heading
    -
      defaultSort:
        - lastName
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'group:1ccad001-55ba-4d90-83b5-00addcccf854' # Job Posters
      tableAttributes:
        - username
        - 'field:a026cacb-2f40-4011-b87d-a1beb7552037' # Organization
      type: native
    -
      key: 'group:d7dc833f-5a4c-4d69-b420-d981939487ea' # BGS Staff
      type: native
email:
  fromEmail: ed+bgs@theblueocean.com
  fromName: 'BlueGreen Sheet'
  replyToEmail: null
  template: _emails/email-layout
  transportSettings:
    host: $SERVD_SMTP_HOSTNAME
    password: $SERVD_SMTP_PASSWORD
    port: $SERVD_SMTP_PORT
    useAuthentication: '1'
    username: $SERVD_SMTP_USERNAME
  transportType: craft\mail\transportadapters\Smtp
fs:
  assets:
    hasUrls: true
    name: Assets
    settings:
      cdnUrlPattern: ''
      customSubfolder: images/
      makeUploadsPublic: true
      optimisePrefix: ''
      optimiseUrlPattern: ''
      projectSlug: ''
      securityKey: ''
      subfolder: local/images/
    type: servd\AssetStorage\AssetsPlatform\Fs
    url: 'https://bluegreen-sheet.files.svdcdn.com'
  attachments:
    hasUrls: true
    name: Attachments
    settings:
      cdnUrlPattern: ''
      customSubfolder: attachments/
      makeUploadsPublic: true
      optimisePrefix: ''
      optimiseUrlPattern: ''
      projectSlug: ''
      securityKey: ''
      subfolder: local/attachments/
    type: servd\AssetStorage\AssetsPlatform\Fs
    url: 'https://bluegreen-sheet.files.svdcdn.com'
meta:
  __names__:
    0d0aac89-9a3b-4d6e-add7-8a1c3a679b77: 'Multi Line Text' # Multi Line Text
    1a3f5855-170a-4899-beb8-07ee6d556899: TBO # TBO
    1ccad001-55ba-4d90-83b5-00addcccf854: 'Job Posters' # Job Posters
    1f0b0042-74ac-4177-b1cf-513c884f116a: 'Paid?' # Paid?
    2a6c91f1-6aa5-4888-bb82-6991538006cb: 'List Items' # List Items
    2d59f6f9-f9d0-47fa-9e56-3a6ca495d7b7: height100 # height100
    2fcab9d0-3904-4d93-95d0-870fccb5c2cc: About # About
    3be9cb9f-6914-4294-a814-3f08c5711c69: 'BGS Overview' # BGS Overview
    3f4d4956-32f9-4440-8020-d01946127d8e: 'BlueGreen Sheet' # BlueGreen Sheet
    5de740b2-aa13-48eb-b460-549297b24e7d: Logos # Logos
    6c8238d6-303b-4cb8-8e3d-dc9cba292c2a: New # New
    6dc842a5-5701-43dd-aefc-62d5112cd1d9: 'Public Schema' # Public Schema
    06ff70cf-8a32-453c-84c8-54a1c71e3e66: 'Payment Type' # Payment Type
    7a6fec95-2ed4-4d18-b669-9108357adc40: 'Single Line Text' # Single Line Text
    7a30d7ad-a979-44b7-89f1-35059c005316: Organizations # Organizations
    7a817dcb-10af-437f-a253-60a5a0e348e3: height50 # height50
    08ba6143-f9a0-4d77-bc74-910ce8990214: 'Job Poster' # Job Poster
    8d320b8b-673d-44d8-9299-bdb93b2c4381: wide250 # wide250
    9b7203f7-538c-4b6c-8119-9c33c258f2bc: 'Privacy & Terms' # Privacy & Terms
    9d8645b3-7788-49d7-92ef-e3c2e0aca352: Logo # Logo
    12d880c0-a281-4f27-a40b-135b2f5b4654: 'Type of Organization' # Type of Organization
    21bd4595-df6f-4876-9708-5bfadad51b42: Website # Website
    31faae40-a08f-430a-aa56-f21a169f7a4b: Privacy # Privacy
    52fe2c65-e3d8-4977-bb85-532fd2435450: 'Organization Name' # Organization Name
    56d41606-0de2-4906-9d56-7a4b768399be: Subscribe # Subscribe
    62b64a73-e162-4b39-97d4-ac8246ccc3e5: 'BlueGreen Sheet' # BlueGreen Sheet
    64e2d70d-bf2d-4df4-9df4-be6545a2afc0: Footer # Footer
    192d4098-f32f-441e-901a-202b4a587a5d: Organization # Organization
    0279dfbc-1019-4d0b-83dc-034b6e185d12: 'Contact Form' # Contact Form
    314e8ab4-95e5-49d8-82e0-08c98192bb23: Jobs # Jobs
    714bebd8-ef6b-4ca1-9139-6f662b0071dd: Simple # Simple
    715d5fae-b704-4b01-8261-112b66dbd693: Capability # Capability
    942ebfb2-eed8-462b-a9fe-651fba4a252f: List # List
    2956ebaa-8a8f-47ad-b082-2754cf28e9b0: Homepage # Homepage
    6407ff57-cf24-424a-8a4f-34c0137e2feb: Country # Country
    676358a4-ad9c-4121-9012-85bcd77506f0: 'Height 400' # Height 400
    7763024f-14a9-49de-8c23-95060f41b140: Facebook # Facebook
    23728677-e935-45a9-be09-8db255d1d4cb: Icon # Icon
    a026cacb-2f40-4011-b87d-a1beb7552037: Organization # Organization
    a05a2d5f-1b66-40d3-b96d-005ae164453b: Benefit # Benefit
    a7ace354-3f52-4d0a-87b1-96da5efcc457: 'Job Attachments' # Job Attachments
    a7f14968-b153-4b66-9ebf-cf75f8135561: About # About
    a614cd34-b5bb-4da6-84ca-e87cdf407ee9: List # List
    abb1d0cc-1e7a-4776-8838-04118e81575a: Hero # Hero
    abe08477-7396-48a3-b1cb-3e492e201e56: Organizations # Organizations
    ac5e09a1-0209-46fa-bf18-00690e21c24e: 'BGS Overview' # BGS Overview
    afc27a98-498b-4fda-8c1e-c5eda8fcc52e: 'Job Region' # Job Region
    b2206c41-3f40-4586-bca2-2bc4fb379556: School # School
    b58343ab-5175-491a-a696-c3a2254d510a: Subscribe # Subscribe
    bb81f5b9-0813-4e6d-b693-229f093ce3e4: 'Job Category' # Job Category
    bc2582f3-84c9-4698-8f75-10e1b877d0a8: Attachments # Attachments
    bfd2eaee-0f5f-44f6-81f2-1f5e563a0e2e: Jobs # Jobs
    c7caf5a7-983c-4d28-9e27-1a7829f7a221: Homepage # Homepage
    c8a0406a-b6dc-4a1e-a316-5a75ff4d23da: 'Job Categories' # Job Categories
    c35140bb-4530-44c6-be76-e4d189e69dd2: 'Stripe Session ID' # Stripe Session ID
    cb2dfb4b-5663-4178-9832-16e186499c56: FAQs # FAQs
    cd9c11b3-1c0d-4a4b-ae79-0936f8f95647: Color # Color
    cdf1f46c-3d43-42f5-9d50-85377f321e61: 'Job Region' # Job Region
    d7dc833f-5a4c-4d69-b420-d981939487ea: 'BGS Staff' # BGS Staff
    db17bc24-8930-4e0e-ab38-c2565b80dae6: 'Rich Text' # Rich Text
    dc90060e-fe9a-4e46-85b1-80079ba69b68: Capability # Capability
    e80d1597-d85d-4dee-b24f-9c30d9facfb2: Benefits # Benefits
    f4e9368b-2d36-4ac5-b087-d0b8a3e8079f: State # State
    f83dc3e4-1815-4b37-abb9-664ad01c8f0b: Footer # Footer
plugins:
  async-queue:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: "/* Sidebar background color */\r\n/* #global-sidebar {\r\n    background: #333f4d;\r\n} */\r\n\r\n/* Header background color */\r\n/* #main-container #main #header {\r\n    background: #ebedef;\r\n} */\r\n\r\n/* H1 tags */\r\n/* h1 {\r\n    color: #29323d;\r\n} */\r\n\r\n\r\n/* Standard button color */\r\n.btn.submit {\r\n    background: #3568aa !important;\r\n}\r\n/* Hover button color */\r\n .btn.submit:not(.disabled):not(.inactive):hover,\r\n.btn.submit:not(.disabled):not(.inactive).hover {\r\n    background: #3b83e1 !important;\r\n}\r\n/* Active button color */\r\n .btn.submit:not(.disabled):not(.inactive):active,\r\n.btn.submit:not(.disabled):not(.inactive).active {\r\n    background: #3568aa !important;\r\n} \r\n\r\n.btn.submit:not(.disabled,.inactive,.loading)[aria-expanded=true] {\r\n    background: #3568aa !important;\r\n}"
      cacheBusting: true
      cssFile: ''
  dashboard-begone:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.14.0
  formie:
    edition: standard
    enabled: true
    licenseKey: M5VU2U4U4XPKMV74PCOE7X7Q
    schemaVersion: 3.4.10
  job-region-populator:
    edition: standard
    enabled: true
    schemaVersion: 1.0.2
  seomatic:
    edition: standard
    enabled: true
    licenseKey: ZMQFBSH3HUF6WI5OS8ZKRG40
    schemaVersion: 3.0.13
  servd-asset-storage:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
    settings:
      adjustFeedmeLogs: ''
      assetsEnvironment: ''
      assetsEnvironmentOverwrite: ''
      cacheClearMode: full
      clearCachesOnSave: always
      clearCdnCacheWhenAssetChanges: '1'
      disableDynamic: ''
      disableTransforms: ''
      fsMapsEnabled: ''
      imageAutoConversion: webp
      injectCors: ''
      projectSlug: bluegreen-sheet
      securityKey: 33ZUmtPqdw2XmcEaxHGVXpczLPw0ykN1
      suppressWarnings: ''
      transformSvgs: 'no'
      useLocalVolumes: false
  stripe:
    edition: standard
    enabled: true
    schemaVersion: 1.2.0
    settings:
      createUserIfMissing: false
      defaultCancelUrl: null
      defaultSuccessUrl: null
      productTemplate: ''
      productUriFormat: ''
      publishableKey: $STRIPE_PUBLISHABLE_KEY
      secretKey: $STRIPE_SECRET_KEY
      syncChangedUserEmailsToStripe: true
      webhookId: ''
      webhookSigningSecret: ''
system:
  edition: pro
  live: true
  name: 'BlueGreen Sheet'
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: America/New_York
