description: 'Blue Green Sheet Staff'
handle: bgsStaff
name: 'BGS Staff'
permissions:
  - accesscp
  - accesscpwhensystemisoff
  - accessplugin-formie
  - accesssitewhensystemisoff
  - administrateusers
  - 'assignusergroup:1ccad001-55ba-4d90-83b5-00addcccf854' # Job Posters
  - 'assignusergroup:d7dc833f-5a4c-4d69-b420-d981939487ea' # BGS Staff
  - assignuserpermissions
  - 'createentries:7a30d7ad-a979-44b7-89f1-35059c005316' # Organizations
  - 'createentries:bfd2eaee-0f5f-44f6-81f2-1f5e563a0e2e' # Jobs
  - 'createfolders:5de740b2-aa13-48eb-b460-549297b24e7d' # Logos
  - 'createfolders:bc2582f3-84c9-4698-8f75-10e1b877d0a8' # Attachments
  - 'deleteassets:5de740b2-aa13-48eb-b460-549297b24e7d' # Logos
  - 'deleteassets:bc2582f3-84c9-4698-8f75-10e1b877d0a8' # Attachments
  - 'deletecategories:c8a0406a-b6dc-4a1e-a316-5a75ff4d23da' # Job Categories
  - 'deleteentries:7a30d7ad-a979-44b7-89f1-35059c005316' # Organizations
  - 'deleteentries:bfd2eaee-0f5f-44f6-81f2-1f5e563a0e2e' # Jobs
  - 'deletepeerassets:5de740b2-aa13-48eb-b460-549297b24e7d' # Logos
  - 'deletepeerassets:bc2582f3-84c9-4698-8f75-10e1b877d0a8' # Attachments
  - 'deletepeercategorydrafts:c8a0406a-b6dc-4a1e-a316-5a75ff4d23da' # Job Categories
  - 'deletepeerentries:7a30d7ad-a979-44b7-89f1-35059c005316' # Organizations
  - 'deletepeerentries:bfd2eaee-0f5f-44f6-81f2-1f5e563a0e2e' # Jobs
  - 'deletepeerentrydrafts:2fcab9d0-3904-4d93-95d0-870fccb5c2cc' # About
  - 'deletepeerentrydrafts:56d41606-0de2-4906-9d56-7a4b768399be' # Subscribe
  - 'deletepeerentrydrafts:64e2d70d-bf2d-4df4-9df4-be6545a2afc0' # Footer
  - 'deletepeerentrydrafts:7a30d7ad-a979-44b7-89f1-35059c005316' # Organizations
  - 'deletepeerentrydrafts:9b7203f7-538c-4b6c-8119-9c33c258f2bc' # Privacy & Terms
  - 'deletepeerentrydrafts:ac5e09a1-0209-46fa-bf18-00690e21c24e' # BGS Overview
  - 'deletepeerentrydrafts:bfd2eaee-0f5f-44f6-81f2-1f5e563a0e2e' # Jobs
  - 'deletepeerentrydrafts:c7caf5a7-983c-4d28-9e27-1a7829f7a221' # Homepage
  - deleteusers
  - 'editimages:5de740b2-aa13-48eb-b460-549297b24e7d' # Logos
  - 'editimages:bc2582f3-84c9-4698-8f75-10e1b877d0a8' # Attachments
  - 'editpeerimages:5de740b2-aa13-48eb-b460-549297b24e7d' # Logos
  - 'editpeerimages:bc2582f3-84c9-4698-8f75-10e1b877d0a8' # Attachments
  - editusers
  - exporter-createexports
  - exporter-deleteexports
  - impersonateusers
  - moderateusers
  - registerusers
  - 'replacefiles:5de740b2-aa13-48eb-b460-549297b24e7d' # Logos
  - 'replacefiles:bc2582f3-84c9-4698-8f75-10e1b877d0a8' # Attachments
  - 'replacepeerfiles:5de740b2-aa13-48eb-b460-549297b24e7d' # Logos
  - 'replacepeerfiles:bc2582f3-84c9-4698-8f75-10e1b877d0a8' # Attachments
  - 'saveassets:5de740b2-aa13-48eb-b460-549297b24e7d' # Logos
  - 'saveassets:bc2582f3-84c9-4698-8f75-10e1b877d0a8' # Attachments
  - 'savecategories:c8a0406a-b6dc-4a1e-a316-5a75ff4d23da' # Job Categories
  - 'saveentries:2fcab9d0-3904-4d93-95d0-870fccb5c2cc' # About
  - 'saveentries:56d41606-0de2-4906-9d56-7a4b768399be' # Subscribe
  - 'saveentries:64e2d70d-bf2d-4df4-9df4-be6545a2afc0' # Footer
  - 'saveentries:7a30d7ad-a979-44b7-89f1-35059c005316' # Organizations
  - 'saveentries:9b7203f7-538c-4b6c-8119-9c33c258f2bc' # Privacy & Terms
  - 'saveentries:ac5e09a1-0209-46fa-bf18-00690e21c24e' # BGS Overview
  - 'saveentries:bfd2eaee-0f5f-44f6-81f2-1f5e563a0e2e' # Jobs
  - 'saveentries:c7caf5a7-983c-4d28-9e27-1a7829f7a221' # Homepage
  - 'savepeerassets:5de740b2-aa13-48eb-b460-549297b24e7d' # Logos
  - 'savepeerassets:bc2582f3-84c9-4698-8f75-10e1b877d0a8' # Attachments
  - 'savepeercategorydrafts:c8a0406a-b6dc-4a1e-a316-5a75ff4d23da' # Job Categories
  - 'savepeerentries:7a30d7ad-a979-44b7-89f1-35059c005316' # Organizations
  - 'savepeerentries:bfd2eaee-0f5f-44f6-81f2-1f5e563a0e2e' # Jobs
  - 'savepeerentrydrafts:2fcab9d0-3904-4d93-95d0-870fccb5c2cc' # About
  - 'savepeerentrydrafts:56d41606-0de2-4906-9d56-7a4b768399be' # Subscribe
  - 'savepeerentrydrafts:64e2d70d-bf2d-4df4-9df4-be6545a2afc0' # Footer
  - 'savepeerentrydrafts:7a30d7ad-a979-44b7-89f1-35059c005316' # Organizations
  - 'savepeerentrydrafts:9b7203f7-538c-4b6c-8119-9c33c258f2bc' # Privacy & Terms
  - 'savepeerentrydrafts:ac5e09a1-0209-46fa-bf18-00690e21c24e' # BGS Overview
  - 'savepeerentrydrafts:bfd2eaee-0f5f-44f6-81f2-1f5e563a0e2e' # Jobs
  - 'savepeerentrydrafts:c7caf5a7-983c-4d28-9e27-1a7829f7a221' # Homepage
  - 'viewassets:5de740b2-aa13-48eb-b460-549297b24e7d' # Logos
  - 'viewassets:bc2582f3-84c9-4698-8f75-10e1b877d0a8' # Attachments
  - 'viewcategories:c8a0406a-b6dc-4a1e-a316-5a75ff4d23da' # Job Categories
  - 'viewentries:2fcab9d0-3904-4d93-95d0-870fccb5c2cc' # About
  - 'viewentries:56d41606-0de2-4906-9d56-7a4b768399be' # Subscribe
  - 'viewentries:64e2d70d-bf2d-4df4-9df4-be6545a2afc0' # Footer
  - 'viewentries:7a30d7ad-a979-44b7-89f1-35059c005316' # Organizations
  - 'viewentries:9b7203f7-538c-4b6c-8119-9c33c258f2bc' # Privacy & Terms
  - 'viewentries:ac5e09a1-0209-46fa-bf18-00690e21c24e' # BGS Overview
  - 'viewentries:bfd2eaee-0f5f-44f6-81f2-1f5e563a0e2e' # Jobs
  - 'viewentries:c7caf5a7-983c-4d28-9e27-1a7829f7a221' # Homepage
  - 'viewpeerassets:5de740b2-aa13-48eb-b460-549297b24e7d' # Logos
  - 'viewpeerassets:bc2582f3-84c9-4698-8f75-10e1b877d0a8' # Attachments
  - 'viewpeercategorydrafts:c8a0406a-b6dc-4a1e-a316-5a75ff4d23da' # Job Categories
  - 'viewpeerentries:7a30d7ad-a979-44b7-89f1-35059c005316' # Organizations
  - 'viewpeerentries:bfd2eaee-0f5f-44f6-81f2-1f5e563a0e2e' # Jobs
  - 'viewpeerentrydrafts:2fcab9d0-3904-4d93-95d0-870fccb5c2cc' # About
  - 'viewpeerentrydrafts:56d41606-0de2-4906-9d56-7a4b768399be' # Subscribe
  - 'viewpeerentrydrafts:64e2d70d-bf2d-4df4-9df4-be6545a2afc0' # Footer
  - 'viewpeerentrydrafts:7a30d7ad-a979-44b7-89f1-35059c005316' # Organizations
  - 'viewpeerentrydrafts:9b7203f7-538c-4b6c-8119-9c33c258f2bc' # Privacy & Terms
  - 'viewpeerentrydrafts:ac5e09a1-0209-46fa-bf18-00690e21c24e' # BGS Overview
  - 'viewpeerentrydrafts:bfd2eaee-0f5f-44f6-81f2-1f5e563a0e2e' # Jobs
  - 'viewpeerentrydrafts:c7caf5a7-983c-4d28-9e27-1a7829f7a221' # Homepage
  - viewusers
