defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: a7f14968-b153-4b66-9ebf-cf75f8135561 # About
handle: about
maxAuthors: 1
name: About
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  62b64a73-e162-4b39-97d4-ac8246ccc3e5: # BlueGreen Sheet
    enabledByDefault: true
    hasUrls: true
    template: about/index.twig
    uriFormat: about
type: single
