defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: f83dc3e4-1815-4b37-abb9-664ad01c8f0b # Footer
handle: footer
maxAuthors: 1
name: Footer
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  62b64a73-e162-4b39-97d4-ac8246ccc3e5: # BlueGreen Sheet
    enabledByDefault: true
    hasUrls: true
    template: footer/_entry.twig
    uriFormat: footer
type: single
